import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Built React bundle directory.
 *
 * The server compiles to dist/web/server.js, so the bundle lives two levels up
 * in dist/web-ui. Keeping them apart means neither build can overwrite the other.
 */
export function webRoot(): string {
  return join(dirname(fileURLToPath(import.meta.url)), "..", "web-ui");
}

export function webAssetPath(relativePath: string): string {
  return join(webRoot(), relativePath.replace(/^\/+/u, ""));
}

export const WEB_CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  // Chrome only treats a manifest as installable when it is served as JSON;
  // the octet-stream fallback would silently disable "Add to Home screen".
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

/** Legacy single-file console, kept as the fallback when dist/web is absent. */
export const DASHBOARD_HTML = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>luban · Agent Workspace</title>
<style>
:root{color-scheme:dark;--bg:#050607;--side:#090b0e;--panel:#101318;--panel2:#151922;--line:#252a34;--fg:#edf0f5;--mut:#9299a8;--dim:#596171;--blue:#72a7ff;--ok:#72d6b5;--err:#f2798b}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;overflow:hidden}button,input,textarea,select{font:inherit;color:inherit}button{cursor:pointer}.app{height:100%;display:grid;grid-template-columns:270px minmax(420px,1fr) 310px}.side,.inspect{display:flex;min-width:0;flex-direction:column;background:var(--side)}.side{border-right:1px solid var(--line)}.inspect{border-left:1px solid var(--line);overflow:auto}
.brand{height:58px;display:flex;align-items:center;gap:10px;padding:0 16px;border-bottom:1px solid var(--line)}.mark{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:var(--fg);color:var(--bg);font-weight:900}.version{margin-left:auto;color:var(--dim);font-size:11px}.new{margin:14px 12px 9px;padding:10px 12px;border:1px solid #343b48;border-radius:10px;background:var(--panel2);text-align:left}.new:hover,.action:hover{border-color:var(--blue)}
.section{padding:10px 14px 7px;color:var(--dim);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.runs{overflow:auto;padding:0 7px 14px}.run{display:block;width:100%;margin:1px 0;padding:9px 10px;border:0;border-radius:8px;background:transparent;text-align:left}.run:hover{background:var(--panel)}.run.active{background:#172033}.run-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.meta{display:flex;align-items:center;gap:6px;margin-top:4px;color:var(--dim);font-size:11px}.dot{width:7px;height:7px;border-radius:50%;background:var(--dim)}.dot.working,.dot.queued{background:var(--blue);box-shadow:0 0 0 3px #72a7ff20}.dot.done,.dot.online{background:var(--ok)}.dot.failed,.dot.cancelled,.dot.offline{background:var(--err)}.foot{margin-top:auto;padding:12px 15px;border-top:1px solid var(--line);display:flex;align-items:center;gap:8px;color:var(--mut);font-size:12px}
.workspace{display:grid;min-width:0;grid-template-rows:58px 1fr auto}.top{display:flex;align-items:center;gap:8px;padding:0 20px;border-bottom:1px solid var(--line)}.title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:650}.pills{display:flex;gap:7px;margin-left:auto}.pill{padding:3px 9px;border:1px solid var(--line);border-radius:99px;color:var(--mut);font-size:11px}.thread{overflow:auto;padding:34px max(22px,calc((100% - 790px)/2))}.empty{height:100%;min-height:380px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.empty .big{font-size:34px}.empty h1{margin:8px 0 5px;font-size:22px}.empty p{margin:0;color:var(--mut)}
.message{display:grid;grid-template-columns:28px 1fr;gap:11px;margin-bottom:24px}.avatar{width:28px;height:28px;border-radius:8px;display:grid;place-items:center;background:var(--panel2);color:var(--mut)}.avatar.user{background:#20314c;color:var(--blue)}.head{color:var(--mut);font-size:12px}.body{margin-top:5px;white-space:pre-wrap;word-break:break-word}.body.error{color:var(--err)}.trace{margin:0 0 24px 39px;padding-left:14px;border-left:1px solid var(--line)}.trace div{padding:4px 0;color:var(--mut);font:12px/1.5 ui-monospace,monospace}.trace .error{color:var(--err)}.running{display:flex;align-items:center;gap:8px;margin:0 0 22px 39px;color:var(--mut);font-size:12px}.spin{width:12px;height:12px;border:2px solid #72a7ff40;border-top-color:var(--blue);border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.composer-wrap{padding:10px max(18px,calc((100% - 830px)/2)) 18px}.composer{overflow:hidden;border:1px solid #333a47;border-radius:13px;background:var(--panel);box-shadow:0 12px 35px #0008}.composer:focus-within{border-color:#72a7ff88}.composer textarea{width:100%;min-height:64px;max-height:180px;padding:14px 15px 7px;resize:none;border:0;outline:0;background:transparent}.composer-row{display:flex;align-items:center;gap:7px;padding:7px 9px}.composer select,.field{min-width:0;padding:7px 8px;border:1px solid var(--line);border-radius:7px;background:var(--panel2);outline:0}.composer select{border:0;background:transparent;color:var(--mut)}.send{width:31px;height:31px;margin-left:auto;border:0;border-radius:8px;background:var(--fg);color:var(--bg);font-weight:900}.send:disabled{opacity:.35}.stop{padding:5px 9px;border:1px solid #f2798b66;border-radius:7px;background:transparent;color:var(--err)}
.block{padding:15px;border-bottom:1px solid var(--line)}.block h2{margin:0 0 10px;color:var(--dim);font-size:11px;letter-spacing:.1em;text-transform:uppercase}.peer{display:flex;align-items:center;gap:8px;padding:5px 0;color:var(--mut);font-size:12px}.peer .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.peer .state{margin-left:auto;font-size:10px}.files{display:flex;flex-direction:column;gap:3px}.file{display:flex;gap:7px;padding:3px 0;color:var(--mut);font-size:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.grid .wide{grid-column:1/-1}.action{padding:7px 9px;border:1px solid var(--line);border-radius:7px;background:var(--panel2);font-size:12px}.action.primary{background:#1b3154;border-color:#31588c}.muted{color:var(--dim)}.toast{position:fixed;right:18px;bottom:18px;display:none;max-width:420px;padding:9px 12px;border:1px solid #39414f;border-radius:9px;background:var(--panel2);box-shadow:0 8px 30px #0009}.toast.show{display:block}@media(max-width:1080px){.app{grid-template-columns:240px 1fr}.inspect{display:none}}@media(max-width:720px){body{overflow:auto}.app{display:block}.side{display:none}.workspace{height:100vh}.thread{padding:24px 16px}.composer-wrap{padding:10px}}
</style></head><body><div class="app">
<aside class="side"><div class="brand"><span class="mark">◈</span><strong>luban</strong><span class="version" id="version">…</span></div><button class="new" id="new">＋ 新任务</button><div class="section">最近任务</div><div class="runs" id="runs"></div><div class="foot"><span class="dot" id="live"></span><span id="node">连接中</span><a href="/docs/" style="margin-left:auto;color:inherit">文档</a></div></aside>
<main class="workspace"><header class="top"><span class="title" id="title">New agent task</span><div class="pills"><span class="pill">AGENT</span><span class="pill" id="model">model</span><span class="pill" id="project-pill">default</span></div></header><section class="thread" id="thread"></section><div class="composer-wrap"><div class="composer"><textarea id="prompt" placeholder="说明目标，Agent 会读取项目、调用工具并验证结果…"></textarea><div class="composer-row"><select id="project"><option value="">default workspace</option></select><span class="muted">Enter 执行 · Shift+Enter 换行</span><button class="send" id="send">↑</button></div></div></div></main>
<aside class="inspect"><div class="block"><h2>Workspace</h2><div class="files" id="files"><span class="muted">工作区为空</span></div></div><div class="block"><h2>Mesh peers</h2><div id="peers"><span class="muted">暂无节点</span></div></div><div class="block"><h2>Inbox</h2><div id="inbox"><span class="muted">暂无消息</span></div></div><div class="block"><h2>Mesh actions</h2><div class="grid"><select class="field wide" id="peer"></select><button class="action" id="push">Sync push</button><button class="action" id="pull">Sync pull</button><input class="field wide" id="message" placeholder="发给节点的消息"><button class="action wide" id="send-message">Send message</button></div></div><div class="block"><h2>Add contact</h2><div class="grid"><input class="field wide" id="contact-name" placeholder="name"><input class="field wide" id="contact-host" placeholder="host"><input class="field" id="contact-port" placeholder="TCP port"><input class="field" id="contact-udp" placeholder="UDP port"><button class="action primary wide" id="add-contact">Save contact</button></div></div></aside>
</div><div class="toast" id="toast"></div><script>
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let S={node:null,jobs:[],peers:[],inbox:[],inboxReady:false,selected:null,detail:null,project:null};
async function api(path,options){const r=await fetch(path,options),b=await r.json();if(!r.ok||b?.ok===false)throw Error(b?.error||('HTTP '+r.status));return b}function ago(t){if(!t)return'';const s=Math.max(0,Date.now()/1000-t);return s<60?Math.floor(s)+'s':s<3600?Math.floor(s/60)+'m':Math.floor(s/3600)+'h'}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function renderRuns(){$('#runs').innerHTML=S.jobs.length?S.jobs.map(j=>'<button class="run '+(j.id===S.selected?'active':'')+'" data-id="'+esc(j.id)+'"><div class="run-title">'+esc(j.title||j.instruction||j.id)+'</div><div class="meta"><span class="dot '+esc(j.status)+'"></span><span>'+esc(j.status)+'</span><span>·</span><span>'+ago(j.created_at)+'</span></div></button>').join(''):'<div class="muted" style="padding:10px">还没有任务</div>';document.querySelectorAll('.run').forEach(e=>e.onclick=()=>selectJob(e.dataset.id))}
function logsHtml(logs){return logs?.length?'<div class="trace">'+logs.map(l=>'<div class="'+(l.level==='error'?'error':'')+'">'+esc('['+(l.level||'info')+'] '+l.msg)+'</div>').join('')+'</div>':''}function renderThread(){const j=S.detail,b=$('#thread');if(!j){b.innerHTML='<div class="empty"><div class="big">◈</div><h1>今天想完成什么？</h1><p>提交任务后由本机 Node Agent 独立执行。</p></div>';$('#title').textContent='New agent task';return}const active=['queued','pending','working'].includes(j.status);$('#title').textContent=j.title||j.id;b.innerHTML='<div class="message"><div class="avatar user">Y</div><div><div class="head">You · '+ago(j.created_at)+'</div><div class="body">'+esc(j.instruction)+'</div></div></div>'+logsHtml(j.logs)+(active?'<div class="running"><span class="spin"></span><span>Agent 正在执行</span><button class="stop" id="stop">停止</button></div>':'')+(j.result?'<div class="message"><div class="avatar">◈</div><div><div class="head">luban · '+esc(j.status)+'</div><div class="body">'+esc(j.result)+'</div></div></div>':'')+(j.error?'<div class="message"><div class="avatar">!</div><div><div class="head">luban · '+esc(j.status)+'</div><div class="body error">'+esc(j.error)+'</div></div></div>':'');if(j.status==='paused'&&j.session_id){b.innerHTML+='<button class="action primary" id="resume">继续任务</button>';$('#resume').onclick=resumeJob}if(active)$('#stop').onclick=cancelJob;b.scrollTop=b.scrollHeight}
async function resumeJob(){const id=S.selected;$('#resume').disabled=true;try{await api('/api/jobs/'+encodeURIComponent(id)+'/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await selectJob(id);await refresh()}catch(e){toast(e.message);await selectJob(id)}}
function renderNode(){const n=S.node;if(!n)return;$('#node').textContent=n.name;$('#live').className='dot online';$('#version').textContent='v'+n.version;$('#model').textContent=n.model||'model';const p=$('#project'),before=p.value,entries=Object.entries(n.projects||{});p.innerHTML='<option value="">default workspace</option>'+entries.map(([k,v])=>'<option value="'+esc(k)+'">'+esc(k)+' · '+esc(String(v).split(/[\\/]/).pop())+'</option>').join('');if(entries.some(([k])=>k===before))p.value=before;$('#project-pill').textContent=p.value||'default'}
function renderPeers(){$('#peers').innerHTML=S.peers.length?S.peers.map(p=>'<div class="peer"><span class="dot '+(p.online?'online':'offline')+'"></span><span class="name">'+esc(p.name)+'</span><span class="state">'+(p.online?'online':'offline')+'</span></div>').join(''):'<span class="muted">暂无节点</span>';$('#peer').innerHTML=S.peers.map(p=>'<option value="'+esc(p.name)+'">'+esc(p.name)+'</option>').join('')}
function renderInbox(){$('#inbox').innerHTML=S.inbox.length?S.inbox.slice(0,8).map(m=>'<div class="peer"><span class="dot online"></span><span class="name"><b>'+esc(m.from)+'</b> · '+esc(m.text)+'</span><span class="state">'+ago(m.received_at)+'</span></div>').join(''):'<span class="muted">暂无消息</span>'}
async function workspace(force=false){const p=$('#project').value;if(!force&&p===S.project)return;S.project=p;try{const r=await api('/api/workspace?project='+encodeURIComponent(p));$('#files').innerHTML=(r.tree||[]).slice(0,40).map(f=>'<div class="file"><span>'+(f.type==='dir'?'▸':'·')+'</span><span>'+esc(f.name)+'</span></div>').join('')||'<span class="muted">工作区为空</span>'}catch(e){$('#files').textContent=e.message}}
async function selectJob(id){S.selected=id;renderRuns();try{S.detail=await api('/api/jobs/'+encodeURIComponent(id));renderThread()}catch(e){toast(e.message)}}async function submit(){const input=$('#prompt'),instruction=input.value.trim();if(!instruction)return;$('#send').disabled=true;try{const r=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instruction,project_id:$('#project').value})});input.value='';await refresh();await selectJob(r.job_id)}catch(e){toast(e.message)}finally{$('#send').disabled=false}}
async function cancelJob(){try{await api('/api/jobs/'+encodeURIComponent(S.selected)+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await selectJob(S.selected)}catch(e){toast(e.message)}}async function meshAction(direction){const peer=$('#peer').value;if(!peer)return toast('请选择节点');try{const r=await api('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({peer,direction,project_id:$('#project').value,mode:'auto'})});toast(r.output)}catch(e){toast(e.message)}}
async function refresh(){try{const [n,p,j,i]=await Promise.all([api('/api/node'),api('/api/peers'),api('/api/jobs'),api('/api/inbox?limit=20')]);const newest=i[0],changed=S.inboxReady&&newest&&newest.id!==S.inbox[0]?.id;S.node=n;S.peers=p;S.jobs=j;S.inbox=i;renderNode();renderPeers();renderInbox();renderRuns();if(changed)toast('📨 '+newest.from+': '+newest.text);S.inboxReady=true;if(S.selected){const found=j.find(x=>x.id===S.selected);if(found&&(!S.detail||found.updated_at!==S.detail.updated_at))await selectJob(S.selected)}workspace()}catch{$('#live').className='dot offline'}}
$('#new').onclick=()=>{S.selected=null;S.detail=null;renderRuns();renderThread();$('#prompt').focus()};$('#send').onclick=submit;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}};$('#project').onchange=()=>{S.project=null;$('#project-pill').textContent=$('#project').value||'default';workspace(true)};$('#push').onclick=()=>meshAction('push');$('#pull').onclick=()=>meshAction('pull');$('#send-message').onclick=async()=>{try{const r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({peer:$('#peer').value,message:$('#message').value})});$('#message').value='';toast(r.output||'消息已送达')}catch(e){toast(e.message)}};$('#add-contact').onclick=async()=>{try{await api('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#contact-name').value,host:$('#contact-host').value,port:Number($('#contact-port').value),udp_port:Number($('#contact-udp').value)})});toast('联系人已保存');await refresh()}catch(e){toast(e.message)}};renderThread();refresh();setInterval(refresh,1800);
</script></body></html>`;

export const DOCS_HTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>luban docs</title><style>body{max-width:850px;margin:40px auto;padding:0 22px;background:#080a0d;color:#e8ecf2;font:15px/1.7 system-ui}code,pre{background:#141820;border-radius:6px}code{padding:2px 5px}pre{padding:14px;overflow:auto}a{color:#72a7ff}</style></head><body><p><a href="/">← 返回控制台</a></p><h1>luban Web API</h1><p>浏览器控制台、Agent worker、Job Store 和 LAN Mesh 均由同一个 Node.js 进程提供，不依赖 Python 后台。</p><h2>启动</h2><pre>luban web . --host 127.0.0.1 --port 8642</pre><h2>API</h2><pre>GET  /api/node /api/peers /api/inbox /api/jobs /api/jobs/:id /api/workspace\nPOST /api/jobs /api/jobs/:id/cancel /api/jobs/:id/resume /api/sync /api/chat /api/contacts\nPOST /api/ping /api/status /api/handoff</pre><p>Web 服务默认只监听本机。需要局域网访问时显式设置 <code>--host 0.0.0.0</code>。</p></body></html>`;
